export default [
  {
    id: 1,
    name: "John Boyega",
    job: "Frontend Developer",
    endorsements: 2300,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657144819/Spekni/user-1_kknjns.png",
      alt: "John Boyega",
    },
    bio: "John Boyega is an excellent Frontend Developer and one of the core maintainers of the React team with a passion for creating quality software using languages like React, JavaScript, NodeJS, Express, Remix, Etc",
    skills: "React, NodeJS, Firebase, NextJS, Python, Vitess, Golang",
    color: "orange",
  },
  {
    id: 2,
    name: "Spiff Jekey Green",
    job: "Backend Developer",
    endorsements: 968,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657623824/Spekni/spiff_yuk6sb.jpg",
      alt: "Spiff Jekey Green",
    },
    bio: "Spiff Jekey Green is an Backend developer and educator who loves creating quality software using languages like NodeJS, DartJS, Laravel, C++, etc.",
    skills: "NodeJS, DartJS, Laravel, C++, Firebase",
    color: "blue",
  },
  {
    id: 3,
    name: "Victor Eke",
    job: "Frontend Developer",
    endorsements: 700,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657623824/Spekni/eke_tuqz8f.png",
      alt: "Victor Eke",
    },
    bio: "Victor Eke is a Senior Frontend developer and educator who loves creating quality software using languages like JavaScipt, NextJS, NodeJS, Firebase,",
    skills: "JavaScipt, NextJS, NodeJS, Firebase, React, Sass, TypeScript",
    color: "green",
  },
  {
    id: 4,
    name: "Bisola Olu",
    job: "Flutter Developer",
    endorsements: 20,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657144819/Spekni/user-2_oied7n.png",
      alt: "Bisola Olu",
    },
    bio: "Bisola Olu is a Flutter Developer and educator who loves creating quality software using languages like Flutter, DartJS, Kotlin, and React Native",
    skills: "Flutter, Dart, Golang, React Native",
    color: "purple",
  },
  {
    id: 5,
    name: "Karim Benzema",
    job: "Senior Software Developer",
    endorsements: 400,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657144819/Spekni/user-3_sqsxou.png",
      alt: "Karim Benzema",
    },
    bio: "Karim Benzema is an Senior Software Developer and educator who loves creating quality software using languages like C++, Python, Java, and ObjectC",
    skills: "C++, Python, Java, ObjectC, Python, Golang, Angular",
    color: "cyan",
  },
  {
    id: 6,
    name: "Rebeccah Liam",
    job: "Shopify Developer",
    endorsements: 208,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657144819/Spekni/user-4_t1x47w.png",
      alt: "Rebeccah Liam",
    },
    bio: "Rebeccah Liam is an Shopify developer and educator who loves creating quality software using languages like Shopify and WordPress",
    skills: "Shopify, Wordpress, AWS cloud, Netlify, Xamp",
    color: "pink",
  },
  {
    id: 7,
    name: "Emeka Paul",
    job: "Android Developer",
    endorsements: 68,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657144819/Spekni/user-7_uajrym.png",
      alt: "Emeka Paul",
    },
    bio: "Emeka Paul is an Android developer and educator who loves creating quality software using languages like Flutter, DartJS, Kotlin, Swift, etc.",
    skills: "Flutter, Dart, Golang, React Native",
    color: "blue",
  },
  {
    id: 8,
    name: "Sophia Turner",
    job: "Backend Developer",
    endorsements: 100,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657144820/Spekni/user-6_wj51gs.png",
      alt: "Sophia Turner",
    },
    bio: "Sophia Turner is a Fullstack Backend developer and educator who loves creating quality software using languages like Python, NodeJS, C++, etc.",
    skills: "Python, NodeJS, C++, Golang",
    color: "yellow",
  },
  {
    id: 9,
    name: "Benjamin Cole",
    job: "Frontend Developer",
    endorsements: 2300,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800888/Spekni/66_plwh9y.png",
      alt: "Benjamin Cole",
    },
    bio: "Benjamin Cole is an excellent Frontend Developer and one of the core maintainers of the React team with a passion for creating quality software using languages like React, JavaScript, NodeJS, Express, Remix, Etc",
    skills: "React, NodeJS, Firebase, NextJS, Python, Vitess, Golang",
    color: "orange",
  },
  {
    id: 10,
    name: "Cindy Ladon",
    job: "Flutter Developer",
    endorsements: 20,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800889/Spekni/78_zo6y8k.png",
      alt: "Cindy Ladon",
    },
    bio: "Cindy Ladon is a Flutter Developer and educator who loves creating quality software using languages like Flutter, DartJS, Kotlin, and React Native",
    skills: "Flutter, Dart, Golang, React Native",
    color: "purple",
  },
  {
    id: 11,
    name: "Pramit Gupta",
    job: "Senior Software Developer",
    endorsements: 400,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800888/Spekni/58_r3y53w.png",
      alt: "Pramit Gupta",
    },
    bio: "Pramit Gupta is an Senior Software Developer and educator who loves creating quality software using languages like C++, Python, Java, and ObjectC",
    skills: "C++, Docker, .Net, Rust, Python, Golang, Angular",
    color: "cyan",
  },
  {
    id: 12,
    name: "Mirabel Tolu",
    job: "Shopify Developer",
    endorsements: 208,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800888/Spekni/30_nml63g.png",
      alt: "Mirabel Olu",
    },
    bio: "Mirabel Olu is an Shopify developer and educator who loves creating quality software using languages like Shopify and WordPress",
    skills: "Shopify, Wordpress, AWS cloud, Netlify, Xamp",
    color: "pink",
  },
  {
    id: 13,
    name: "Mike Chen",
    job: "Android Developer",
    endorsements: 68,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800887/Spekni/90_u9ltbe.png",
      alt: "Mike Chen",
    },
    bio: "Mike Chen is an Android developer and educator who loves creating quality software using languages like Flutter, DartJS, Kotlin, Swift, etc.",
    skills: "Flutter, Dart, Golang, React Native",
    color: "blue",
  },
  {
    id: 14,
    name: "Kim Helen",
    job: "Backend Developer",
    endorsements: 100,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800887/Spekni/44_akl5ap.png",
      alt: "Kim Helen",
    },
    bio: "Kim Helen is a Fullstack Backend developer and educator who loves creating quality software using languages like Python, NodeJS, C++, etc.",
    skills: "Python, NodeJS, C++, Golang",
    color: "yellow",
  },
  {
    id: 15,
    name: "Antonio Carlos",
    job: "Frontend Developer",
    endorsements: 2300,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800888/Spekni/14_uy57ue.png",
      alt: "Antonio Carlos",
    },
    bio: "Antonio Carlos is an excellent Frontend Developer and one of the core maintainers of the React team with a passion for creating quality software using languages like React, JavaScript, NodeJS, Express, Remix, Etc",
    skills: "React, NodeJS, Firebase, NextJS, Python, Vitess, Golang",
    color: "orange",
  },
  {
    id: 16,
    name: "Clara Mikasa",
    job: "Flutter Developer",
    endorsements: 20,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800887/Spekni/99_bsdhcr.png",
      alt: "Clara Mikasa",
    },
    bio: "Clara Mikasa is a Flutter Developer and educator who loves creating quality software using languages like Flutter, DartJS, Kotlin, and React Native",
    skills: "Flutter, Dart, Golang, React Native",
    color: "purple",
  },
  {
    id: 17,
    name: "Hinata Kimiko",
    job: "Senior Software Developer",
    endorsements: 400,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800889/Spekni/85_rdz3zj.png",
      alt: "Hinata Kimiko",
    },
    bio: "Hinata Kimiko is an Senior Software Developer and educator who loves creating quality software using languages like C++, Python, Java, and ObjectC",
    skills: "C++, Docker, .Net, Rust, Python, Golang, Angular",
    color: "cyan",
  },
  {
    id: 18,
    name: "Chuck Bartowski",
    job: "Shopify Developer",
    endorsements: 208,
    favoured: false,
    image: {
      url: "https://res.cloudinary.com/victoreke/image/upload/v1657800888/Spekni/51_duxpdt.png",
      alt: "Chuck Bartowski",
    },
    bio: "Chuck Bartowski is an Shopify developer and educator who loves creating quality software using languages like Shopify and WordPress",
    skills: "Shopify, Wordpress, AWS cloud, Netlify, Xamp",
    color: "pink",
  },
];
